### ISSUE TITLE
All incoming calls are not recorded at once, they have to be selected and recorded separately

### ISSUE THREAD

**Issue by masshuvo** [Xposed-Modules-Repo/io.github.vvb2060.callrecording#5]
![Screenshot_2023-06-10-10-24-04-402_com google android dialer](https://github.com/Xposed-Modules-Repo/io.github.vvb2060.callrecording/assets/108648096/94d57994-eede-4895-9932-3560f8926a39)

All call dialer applications have an option to automatically record every incoming call, but I didn't find it here in your Google dialer Lsposed Module.

**Comment by vvb2060** [comment]
https://support.google.com/phoneapp/answer/9803950
expected behavior
